version: 2.1
orbs:
  win: circleci/windows@2.4.1
docker:
  - image: circleci/node:14.17.6
  - image: circleci/npm:6.14.15
jobs:
  build-test:
    working_directory: ~/live-posts
    executor: 
        name: win/default
        shell: bash.exe
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm i
      - run: 
          name: Install Angular
          command: npm install -g @angular/cli
      - run: 
          name: Build App
          command: ng build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - nodes_modules
      - run:
          name: Run Unit Test
          command: ng test
workflows:
  build_and_test:
    jobs:
      - build-test
